---
- hosts: local
  remote_user: ec2-user
  tasks:
    - name: Creating an ec2-Instance
      ec2:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        count: 1
        group_id: sg-0ac4b7d3252eab0fa
        image: ami-9c0638f9
        instance_type: t2.micro
        key_name: Praveen-AWS
        region: us-east-2
        vpc_subnet_id: subnet-0d06821448c851ca9
        zone: us-east-2a
        termination_protection: no
        wait: yes
        instance_tags: 
          Name: centos
        volumes:
        - device_name: /dev/sda1
          volume_size: 8
          volume_type: gp2
          delete_on_termination: true
        assign_public_ip: no
      register: ec2

    - name: adding a line into the hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "{{ item.private_ip }}"
        insertafter: 'nodes'
      with_items: "{{ ec2.instances }}"
      loop_control:
        label: "{{ item.private_ip }}"

    - name: trying to execute few lines on new Instance
      shell: sleep 25s

    - name: Refreshing inventory file
      meta: refresh_inventory

- hosts: nodes
  become: yes
  remote_user: centos
  tasks:
    - name: Installing the docker
      yum: 
        name: docker
        state: latest

    - name: starting the docker service
      service:
        name: docker
        state: started

    - name: Installing pip
      shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py

    - name: Installing the docker-py
      pip:
        name: docker-py

    - name: Running the container
      docker_container:
        name: jenkins
        image: praveenvp/softwares:jenkins
        pull: yes
        state: started
        ports:
          - "8080:8080"
      tags: container

