---
- hosts: local
  remote_user: ec2-user
  tasks:
    - name: Creating an ec2-Instance
      ec2:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        count: 1
        group_id: sg-0ac4b7d3252eab0fa
        image: ami-922914f7
        instance_type: t2.micro
        key_name: Praveen-AWS
        region: us-east-2
        vpc_subnet_id: subnet-0d06821448c851ca9
        zone: us-east-2a
        termination_protection: no
        wait: yes
        instance_tags: 
          Instance: node-2
        volumes:
        - device_name: /dev/xvda
          volume_size: 8
          volume_type: gp2
          delete_on_termination: true
        private_ip: 192.168.2.14
        assign_public_ip: no
      register: ec2
      tags: create_Instance

    - name: adding a line into the hosts file
      lineinfile:
        path: /etc/ansible/hosts
        line: "{{ item.private_dns_name }}"
        insertafter: 'nodes'
      with_items: "{{ ec2.instances }}"
      tags: create_Instance
