---
- hosts: local
  user: ec2-user
  vars_files:
    - ./ec2_vars.yml
  tasks:
  - name: creating an ec2 instance
    ec2:
      aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      key_name: "{{ ec2['key_name'] }}"
      instance_type: "{{ ec2['instance_type'] }}"
      image: "{{ ec2['image'] }}"
      region: "{{ ec2['region'] }}"
      zone: "{{ ec2['zone'] }}"
      wait: yes
      group: "{{ ec2['group'] }}"
      vpc_subnet_id: "{{ ec2['vpc_subnet_id'] }}"
      assign_public_ip: "{{ ec2['assign_public_ip'] }}"
      count: "{{ ec2['count'] }}"
      volumes:
      - device_name: "{{ ec2_vol['device_name'] }}"
        volume_size: "{{ ec2_vol['volume_size'] }}"
        volume_type: "{{ ec2_vol['volume_type'] }}"
        delete_on_termination: "{{ ec2_vol['delete_on_termination'] }}" 
      instance_tags:
        Name: "{{ ec2_ins_tags['value'] }}"
    register: ec2Instance

  - name: Adding the PrivateIP to the Inventory file
    lineinfile:
      path: "{{ ansible_inventory['hosts'] }}"
      line: "{{ item.private_ip }}"
      insertafter: "{{ ansible_inventory['group'] }}"
    with_items: "{{ ec2Instance.instances }}"
