---
- hosts: local
  remote_user: ec2-user
  gather_facts: False
  vars: 
    hivar: hello      
  vars_files:
    - ./variables.yml
  tasks:
    - name: copy the ansible hosts file to node-1
      copy:
        src: /etc/ansible/hosts 
        dest: /home/ec2-user

    - name: adding a line into the hosts file
      lineinfile:
        path: /home/ec2-user/Learn/DevOps/Ansible/Playbooks/hosts
        line: 192.168.2.80
        insertafter: 'node-1'

    - name: Working on variables
      shell: echo "The variable value is:" "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}" "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: output
      tags: variable

    - name: display the result
      debug:
        msg: "{{ output.stdout }}"
      tags: variable

    - name: delete a file
      file:
        dest: /home/ec2-user/Learn/DevOps/Ansible/Playbooks/ex.txt
        state: absent
      tags: try_file

    - name: add entry
      add_host:
        groups: giveatry
        name: 193.168.2.5
      tags: tryaddhost
